[project]
name = "vc-knn-practice-2026-2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "attrs>=26.1.0",
    "backcall>=0.2.0",
    "bleach>=6.4.0",
    "certifi>=2026.7.22",
    "chardet>=7.6.0",
    "colorama>=0.4.6",
    "cycler>=0.12.1",
    "cython>=3.3.0",
    "decorator>=5.3.1",
    "defusedxml>=0.7.1",
    "entrypoints>=0.4",
    "future>=1.0.0",
    "gitdb2>=4.0.2",
    "gitpython>=3.1.62",
    "idna>=3.20",
    "imageio>=2.37.4",
    "ipykernel>=7.3.0",
    "ipython>=9.16.1",
    "ipython-genutils>=0.2.0",
    "ipywidgets>=8.1.9",
    "jedi>=0.20.0",
    "jinja2>=3.1.6",
    "jsonschema>=4.26.0",
    "jupyter>=1.1.1",
    "jupyter-client>=8.9.1",
    "jupyter-console>=6.6.3",
    "jupyter-core>=5.9.1",
    "jupyterlab-server>=2.28.1",
    "kiwisolver>=1.5.0",
    "markupsafe>=3.0.3",
    "matplotlib>=3.11.1",
    "mistune>=3.3.4",
    "nbconvert>=7.17.1",
    "nbdime>=4.0.4",
    "nbformat>=5.11.1",
    "notebook>=7.6.3",
    "numpy>=2.5.2",
    "pandocfilters>=1.5.1",
    "parso>=0.8.7",
    "pexpect>=4.9.0",
    "pickleshare>=0.7.5",
    "pillow>=12.3.0",
    "prometheus-client>=0.26.0",
    "prompt-toolkit>=3.0.53",
    "ptyprocess>=0.7.0",
    "pygments>=2.21.0",
    "pyparsing>=3.3.2",
    "pyrsistent>=0.20.0",
    "python-dateutil>=2.9.0.post0",
    "pyzmq>=27.2.0",
    "qtconsole>=5.7.2",
    "requests>=2.34.2",
    "scipy>=1.18.1",
    "send2trash>=2.1.0",
    "six>=1.17.0",
    "smmap2>=3.0.1",
    "terminado>=0.18.1",
    "testpath>=0.6.0",
    "tornado>=6.5.8",
    "traitlets>=5.16.1",
    "urllib3>=2.8.0",
    "wcwidth>=0.8.2",
    "webencodings>=0.6.1",
    "widgetsnbextension>=4.0.16",
]

[tool.pyright]
extraPaths = ["src/notebooks"]
venvPath = "."
venv = ".venv"
